server:
  port: 8082
spring:
  security:
    saml2:
      relyingparty:
        registration:
          idenfit:
            assertingparty:
              metadata-uri: https://dev-api.testing.idenfit.com/saml/metadata